name: Home Assistant

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hassfest:
    name: Hassfest
    runs-on: self-hosted
    steps:
      - name: â¤µï¸ Checkout repository
        uses: actions/checkout@v6
      - name: ğŸ” Analyse with Hassfest
        uses: home-assistant/actions/hassfest@master
  hacs:
    name: HACS
    runs-on: self-hosted
    steps:
      - name: â¤µï¸ Checkout repository
        uses: actions/checkout@v6
      - name: ğŸ” Analyse with hacs
        uses: hacs/action@main
        with:
          category: integration
